---
abstract: 'interface to directory of files'
author:
  - 'Ken Williams (ken@mathforum.org)'
build_requires:
  Test: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-TextDir
provides:
  Tie::TextDir:
    file: TextDir.pm
    version: '0.07'
requires:
  Carp: '0'
  Fcntl: '0'
  File::Find::Iterator: '0.4'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  Symbol: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
